ROX-14418: Get ENP up and running
stackrox/external-network-pusher pull request #24
Opened 2023-04-11 09:27 UTC by Maddosaurus

2023-04-11 16:21 UTC, vikin91 reviewed
It looks really good! 
I have some questions and optional suggestions.

2023-04-11 16:21 UTC, vikin91 commented on .github/workflows/push-networks.yaml
> +    - synchronize
Why do we want to run this on PRs?

2023-04-11 16:21 UTC, vikin91 commented on .github/workflows/push-networks.yaml
>  name: Build external-network-pusher
I know you did not change it, but is this action really building it? I think that calling it `Run external-...` would make it clear. Or better: `Update external network definitions on definitions.stackrox.io`

2023-04-11 16:21 UTC, vikin91 commented on .github/workflows/push-networks.yaml
> +        run:  linux/network-crawler --dry-run --bucket-name definitions.stackrox.io  # FIXME: Remove dry-run flag here
Is the resulting file that would be pushed viewable/readable for the human? Could we maybe print it to the action output, so that we know what go written?

Other ideas: Could we download the previous file from definitions.stackrox.io before overwriting it and print it too? Maybe with some diff as well. This would help us understand in the future what this tool is actually doing.

(If the bucket is versioned, then the suggestions from this comment have less value, but I wanted to ask anyway)

2023-04-11 16:22 UTC, vikin91 commented on .github/workflows/push-networks.yaml
> +    - synchronize
Ups, I see now, that we are not in Stackrox repo 🤦  Sorry, please ignore this comment :)

2023-04-11 16:23 UTC, vikin91 approved these changes
LGTM, but please let Tom give it a quick look before merging.

2023-04-11 16:46 UTC, Maddosaurus commented on .github/workflows/push-networks.yaml
> +    - synchronize
The idea is to build, test, and do a dry-run on PRs against this repo to ensure that the resulting binary will succeed 😄 
We're not in our main repo, so this should be fine, as it's the only automated check that is running.

2023-04-11 16:49 UTC, Maddosaurus commented on .github/workflows/push-networks.yaml
>  name: Build external-network-pusher
I did introduce the name, but it was in an earlier PR. I agree that `build` is not exactly accurate.
I like `Update external network definitions` better, let me think about it and see what I can come up with.

2023-04-12 06:11 UTC, tommartensen commented on .github/workflows/push-networks.yaml
> +          install_components: "gke-gcloud-auth-plugin"
```suggestion
```

This is only required if you want to authenticate to a GKE cluster, you can remove these two lines.

2023-04-12 06:12 UTC, tommartensen commented on .github/workflows/push-networks.yaml
> +          install_components: "gke-gcloud-auth-plugin"
```suggestion
```

See above.

2023-04-12 06:13 UTC, tommartensen commented on .github/workflows/push-networks.yaml
> +        continue-on-error: false
What is the reason for `continue-on-error` ?

2023-04-12 06:15 UTC, tommartensen requested changes
Two suggestions and a question.

One more thing to consider: How do you want to monitor job success for the scheduled runs?

2023-04-12 07:55 UTC, Maddosaurus commented on .github/workflows/push-networks.yaml
> +        continue-on-error: false
This was a carry over from the kubelinter workflow I based this one on.
From what I can see, this is set to `false` by default anyways, so I might as well remove it from here.

2023-04-12 08:05 UTC, tommartensen commented
> There are mail notifications that are being sent out if a job fails, but maybe you have a different mechanism in mind?
My gut feeling tells me something like a Slack bot posting to acs-nightly-ci-runs or acs-test-failures might also not be a bad idea. WDYT?

From https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/notifications-for-workflow-runs: 

> Notifications for scheduled workflows are sent to the user who initially created the workflow. If a different user updates the cron syntax in the workflow file, subsequent notifications will be sent to that user instead. If a scheduled workflow is disabled and then re-enabled, notifications will be sent to the user who re-enabled the workflow rather than the user who last modified the cron syntax.

Mail notifications to a user (who might or might not read their emails, leave the organization, ...) sounds like a single point of failure to me. I'll leave the decision to you and give you a LGTM already.

2023-04-12 08:05 UTC, tommartensen approved these changes
LGTM

2023-04-12 15:02 UTC, Maddosaurus commented
@tommartensen I have added Slack notifications for a team Maple channel. Please feel free to take another look [here](https://github.com/stackrox/external-network-pusher/pull/24/files#diff-920dae94a370229ec0d6613197b3d00e75ed7942250e00ff40d6414d48f61195R120).

@vikin91 I've renamed the workflow and added a [download of the current networks and checksum](https://github.com/stackrox/external-network-pusher/pull/24/files#diff-920dae94a370229ec0d6613197b3d00e75ed7942250e00ff40d6414d48f61195R21) before overwriting them. They will show up in the artifacts tab of a run and will be cached for 60 days. [Example here](https://github.com/stackrox/external-network-pusher/actions/runs/4676819671) (see "Artifacts" at the bottom).

2023-04-13 06:27 UTC, tommartensen commented
@Maddosaurus - Slack notification LGTM

2023-04-13 07:27 UTC, merged